language: minimal
services:
  - docker
env:
  - TAG=jessie
  - TAG=stretch
  - TAG=stretch-slim
  - TAG=buster
  - TAG=buster-slim
script:
  - cd $TAG
  - docker build --no-cache --pull -t wisvch/debian:$TAG -t quay.io/wisvch/debian:$TAG .
deploy:
  - provider: script
    script: >-
      sh -c '
      docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
      echo pushing to wisvch/debian:$TAG;
      docker push wisvch/debian:$TAG;
      '
    on:
      branch: master
  - provider: script
    script: >-
      sh -c '
      docker login -u "$QUAY_USERNAME" -p "$QUAY_PASSWORD" quay.io;
      echo pushing to quay.io/wisvch/debian:$TAG;
      docker push quay.io/wisvch/debian:$TAG;
      '
    on:
      branch: master
notifications:
  email: false
  slack:
    rooms:
      secure: Ul3RZ1kDu1/rVqzPjP0FgrRagJkAhhdBcGUv7fIB4ulBXKZ7Vz9wfERDWMn889ecTibxp5JrDA0AzVNAth5v7oU/n7BV69plBksvK90vEPu0p6Vg8cLwM8HsACgv86idHEu29Hy6Aqo0XfHnbao23s2oPpoA8nkb5TILCpUe0JzbGiajlzmjQfPWCEjdjvhm7kk1C68uvxnQ6bQdKGxqklzdr7E7M51a02vhCQtJTGEbcSNX3WlNOyXGEMYrA4ha7aPlroVLmwYn5tIbVtfMXMk5y/j0bvVIa21UZ6KsVVCXme2rMvio6dQvLmZ9WCbLv3exRX9rs8iL5c1R4ZKVQCAZwPm6VUbsA3617wFt8tjfcZtkGYtd41p+dpGk+VeK6RpSjmDpu9ZUUrtJaeHOTKBJRBrMRHLMnyxrJBhVC2ntFJVPj73Erdfj3zkny0Wuz9GWbir6bTWjAPm/pJ8dUviVkXmbdugL/uaBedPWdsN4z6AFp61Ht9sGOO+EP2p6mYvtOuM6w6oCbPSi/ascglh01zlwUnub8/+ZJEMQKxG6xD6PIBAYm9+LmSLO7MStxJc1RBu+zwTd36mbuXAHsO8O79qPs4kt6OSgb4Z1ifRL8PfUNW4OhfEkG3ESq74B0mG83jOC9UYTg+7F6GxaejklO2Wl3TTUiaZUksTx9DI=
