name: Docker
on:
  push:
  workflow_dispatch:
  schedule:
  - cron: "54 2 2 * *"
jobs:
  buildDockerImage:
    name: Build Docker image
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tag:
        - "buster"
        - "buster-slim"
        - "bullseye"
        - "bullseye-slim"
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: ${{ matrix.tag }}
        tags: ghcr.io/wisvch/debian:${{ matrix.tag }}
        push: ${{ github.ref == 'refs/heads/master' }}
